### ISSUE TITLE
Missing type of list in presentation XML

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/isodoc#333]
Source issues:
- https://github.com/metanorma/ogc-citygml-xmi/issues/103
- https://github.com/metanorma/ogc-citygml-xmi/issues/117

In the source presentation xml for the document OGC 20-010 there aren't attribute `type` for some `ol`:
```xml
<ol>
  <li>
    <p id="_...">For each UML class defined or referenced in the Tunnel Package:</p>
      <ol>
        <li>
          <p id="_...">Validate that the Implementation Specification contains a data element which represents the same concept as that defined for the UML class.</p>
       </li>
```
```xml
<term id="term-conceptual-schema">
	<name>4.1.7.</name>
	<preferred>conceptual schema</preferred>
	<definition>
		<ol>
			<li>
				<p id="_">formal description of a <em>conceptual model</em> (<xref target="term-conceptual-model">Clause 4.1.6</xref>)</p>
				<termsource status="identical">

```

**Comment by opoudjis** [comment]
Yeah, I add those lists to term definitions in a later stage of processing (isodoc Presentation XML), and I'll need to reinsert the typing of lists from the earlier stage of processing (asciidoc postprocessing).

**Comment by opoudjis** [comment]
... A real solution to this, that will resolve list depth consistently in both isodoc and asciidoc, across all flavours, will require refactoring of how list styles are realised—to ensure that styles are implemented on XML as much as possible, rather than assumed inherited from asciidoc, as is the case in standoc and (by inheritance) OGC.

... So I'd like to not resolve this immediately. For now, please assume in OGC a default style of "arabic".

**Comment by opoudjis** [comment]
Duplicated as https://github.com/metanorma/isodoc/issues/245. All //ol now have type in Presentation XML.
