### ISSUE TITLE
Crash on table generation in SS 584 document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#383]
https://github.com/metanorma/ss-584/issues/4

**Comment by opoudjis** [comment]
The issue is that a rowspan of 10 has been specified in a table cell that has only 9 rows left to span.

The real reason for this is a markup error: a cell divider has been left out, so the rows are being miscounted.

I have introduced defensive coding in Word, which deals with too many rows specified in rowspan; but PDF generation is crashing.

**Comment by opoudjis** [comment]
The real solution is to repair this in Presentation XML.

**Comment by opoudjis** [comment]
I do abort if rowspan is misused. Turns out I cannot abort if colspan is misused, because if it is, Asciidoc refuses to generate the table: Asciidoc enforces consistent column counts in tables. I'm keeping the validation code for column count just in case, anyway.
