### ISSUE TITLE
GitHub Actions not responding to Pull Requests

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#456]
https://github.com/metanorma/isodoc/commit/cde8574eaaa450675a9f3a855bec056b8c517f5e

**Comment by CAMOBAP** [comment]
@opoudjis as far as I see there is no PR created for fix/plural-localities

Currently all our repos configured such way that we run CI when:
 - push to main
 - tag with `v` prefix
 - pull_request opened

This sams reasonable to be because not always we need to run CI on feature/bugfix branches. If you need such - just create a pull request

**Comment by opoudjis** [comment]
Right, so what is actually happening is that it's ignoring my request to create a PR. I'll need to work out why, but this isn't the issue.
