### ISSUE TITLE
Crashes when using code blocks with tags

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#499]
The presence of tags description at the bottom of the list crashes isodoc.

```adoc
.Terms and definitions in Metanorma AsciiDoc
[source,adoc]
----
== Terms and definitions <1>

=== conceptual model <2>
alt:[CM] <3>

model that defines concepts of a universe of discourse <4>

[.source]
<<ISO_19101-1,clause=4.1.5>> <5>

=== logical model

model that implements a {{conceptual model}} at a logical level <6>
----
<1> Mandatory clause title
<2> Term for concept
<3> Alternate term for concept
<4> Definition of concept
<5> Source of concept
<6> Concept mention of a defined term in the same document
```

```sh
undefined method `text' for nil:NilClass

          div << "<span class='c'>&lt;#{callout.text}&gt;</span> "
                                               ^^^^^
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/blocks.rb:104:in `block in annotation_parse'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/blocks.rb:100:in `annotation_parse'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/to_word_html.rb:190:in `parse'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/blocks.rb:89:in `block in sourcecode_parse1'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/blocks.rb:89:in `sourcecode_parse1'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/html_function/html.rb:97:in `block in sourcecode_parse'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/html_function/html.rb:96:in `sourcecode_parse'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/to_word_html.rb:188:in `parse'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/section.rb:15:in `block (2 levels) in clause_parse'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/section.rb:14:in `each'
lib/ruby/gems/3.1.0/gems/isodoc-2.5.0/lib/isodoc/function/section.rb:14:in `block in clause_parse'
```

**Comment by opoudjis** [comment]
Cannot replicate, need context.

This *always* happens, as you know.

**Comment by opoudjis** [comment]
So, what I need to do is issue explicit fatal errors where I don't already.

**Comment by opoudjis** [comment]
Of these, "When the key's anchor reference cannot be resolved" at least is already raised, but it needs to be fatal.

**Comment by opoudjis** [comment]
I had attempted to improve the error reporting for annotations by reproducing the number of the annotation that might not match the callout. It turns out however that Asciidoctor does NOT preserve the annotation numbering; it overwrites it with sequential numbering during processing. So if `<1> <2>` are annotated with `<3> <4>`, I never get to see the `<3> <4>` in processing: all the information I have is that there are two annotations. Accordingly, I cannot report  `<1> <2>` annotated with `<3> <4>` as an error: by the time it gets to me, it is  `<1> <2>` annotated with `<1> <2>`.

**Comment by opoudjis** [comment]
> When the anchor is malformed
> When the key's anchor reference is malformed

This is sourcecode. If Asciidoctor does not see a `<\d+>`, it will ignore it.

So the following:

````
.Terms and definitions in Metanorma AsciiDoc
[source,adoc]
----
== Terms and definitions <<1>

=== conceptual model <2
alt:[CM] <3>

model that defines concepts of a universe of discourse <4>

[.source]
<<ISO_19101-1,clause=4.1.5>> <5>

=== logical model

model that implements a {{conceptual model}} at a logical level <6>
----
<<1> Mandatory clause title
<2 Term for concept
<3> Alternate term for concept
<4> Definition of concept
<5> Source of concept
<6> Concept mention of a defined term in the same document
````

Results in `<<1>` recognised as a callout (with an additional initial `<`);  `<2` is not recognised as a callout at all; and because the initial annotation markup is mangled, no annotations are recognised (the `<\d+>` constitute a list): Metanorma detects 5 callouts and 0 annotations, and crashes, and the parse saved in .xml.abort makes it clear what has happened:

````
<sourcecode id="_fac0d518-8274-ae4b-6636-284cd02d763e" lang="adoc"><name>Terms and definitions in Metanorma AsciiDoc</name>== Terms and definitions &lt;<callout>1</callout>

=== conceptual model &lt;2
alt:[CM] <callout>3</callout>

model that defines concepts of a universe of discourse <callout>4</callout>

[.source]
&lt;&lt;ISO_19101-1,clause=4.1.5&gt;&gt; <callout>5</callout>

=== logical model

model that implements a {{conceptual model}} at a logical level <callout>6</callout></sourcecode>


<p id="_ba0bcde9-54e5-bce0-397d-9dcf335c9886">&lt;&lt;1&gt; Mandatory clause title
&lt;2 Term for concept
&lt;3&gt; Alternate term for concept
&lt;4&gt; Definition of concept
&lt;5&gt; Source of concept
&lt;6&gt; Concept mention of a defined term in the same document</p>
````

There is nothing more I can do to intervene in this model; Asciidoctor is too opinionated for me to detect malformed callouts or annotations, they simply are not parsed, and more importantly, the document is aborting anyway because the requisite number of matching callouts and annotations is not detected.

Nothing more to do here.

**Comment by opoudjis** [comment]
@ronaldtse 

https://github.com/metanorma/metanorma-standoc/issues/764

> When the target item links `<1>` are present in the source code but the target item list is not present, Metanorma should treat the Key as missing but do not crash.

Since the error of missing targets *was* being highlighted before, I assumed you wanted there to be a crash rather than just a random fail if the link was missing. You are now saying that you want a

**Comment by opoudjis** [comment]
I guess so.
